### ISSUE TITLE
IDA9.0 doesn't seem to show the icon after putting it in the plugin directory

### ISSUE THREAD

**Issue by zhefox** [EngineLessCC/ClassInformer-IDA-90#1]
![image](https://github.com/user-attachments/assets/a738604c-33d5-4a34-9b9d-b846499a92d3)

maybe it not loaded

**Comment by enginelesscc** [comment]
use the dll from the release, not the code, the ones in code are outdated
ps: there is only "IDAClassInformerPlugIn64.dll"

**Comment by zhefox** [comment]
![image](https://github.com/user-attachments/assets/f82afec1-ec84-4293-8258-838195b2f7b1)
![image](https://github.com/user-attachments/assets/66c45df0-a0ea-4b52-bb4c-2f583535dcdc)
It still doesn't seem to work, T_T

**Comment by zhefox** [comment]
oh,wait, I haven't used your updated version yet

**Comment by zhefox** [comment]
![image](https://github.com/user-attachments/assets/853d0222-b78a-450f-9535-40dab2b1241b)

It's weird, it's still not loading, and it's not even an error

**Comment by c6-dev** [comment]
Loaded and worked fine for me through Edit-Plugins-Class Informer

**Comment by enginelesscc** [comment]
Edit > Plugins > Class Informer

![image](https://github.com/user-attachments/assets/d777b2d1-9643-41e2-ae10-61fe49fa0663)

**Comment by zhefox** [comment]
oh,yeah,It looks fine and works,happy~

**Comment by enginelesscc** [comment]
Keep in mind though its a bit hacky, the v9 beta api and sdk arent finished yet so i commented some code
